import "./globals.css";
import { Open_Sans } from "next/font/google";

const sans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={sans.className}>
      <body className="container mx-auto flex min-h-screen flex-col justify-between">
        <header className="flex justify-between">
          <h1 className="text-2xl font-bold">{"kihyeon's blog"}</h1>
          <nav className="flex space-x-4">
            <div>home</div>
            <div>about</div>
            <div>posts</div>
            <div>contact</div>
          </nav>
        </header>
        {children}
        <footer className="bg-black text-center text-white">
          ki hyeon | All Right Reserved.
        </footer>
      </body>
    </html>
  );
}
