import Link from "next/link";
import "./globals.css";
import { Open_Sans } from "next/font/google";

const sans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={sans.className}>
      <body className="container mx-auto flex min-h-screen flex-col">
        <header className="flex justify-between">
          <Link href="/">
            <h1 className="text-2xl font-bold">{"kihyeon's blog"}</h1>
          </Link>
          <nav className="flex space-x-4">
            <Link href="/">home</Link>
            <Link href="/about">about</Link>
            <Link href="/posts">posts</Link>
            <Link href="/contact">contact</Link>
          </nav>
        </header>
        <main className="flex grow flex-col">{children}</main>
        <footer className="bg-black text-center text-white">
          ki hyeon | All Right Reserved.
        </footer>
      </body>
    </html>
  );
}
